import { mkdir, readdir, readFile, writeFile } from 'fs/promises';
import { basename, dirname, join } from 'path';

const ICONS_DIR = join(process.cwd(), 'src/assets/images/icons');
const COMPONENT_DIR = join(process.cwd(), 'src/app/components/icon');
const TYPES_FILE = join(COMPONENT_DIR, 'icon.generated.types.ts');
const README_FILE = join(COMPONENT_DIR, 'README.md');

async function generateIconTypes() {
  try {
    const files = await readdir(ICONS_DIR);
    const svgFiles = files.filter((file) => file.startsWith('icon-') && file.endsWith('.svg'));
    const iconNames: string[] = [];

    for (const file of svgFiles) {
      const filePath = join(ICONS_DIR, file);
      let content = await readFile(filePath, 'utf-8');

      // Extract inner content
      const innerMatch = content.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i);
      if (!innerMatch) continue;
      let inner = innerMatch[1].trim();

      // Clean inner attributes
      inner = inner.replace(/\s\b(class|b8ns[0-9]+|data-[a-z0-0-]+)\b(=("[^"]*"|'[^']*'))?/gi, '');

      // Normalize colors
      inner = inner.replace(/\b(fill|stroke)="((?!none)[^"]*)"/gi, '$1="currentColor"');

      // Reconstruct SVG
      const cleanSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  ${inner}
</svg>`;

      await writeFile(filePath, cleanSvg, 'utf-8');
      iconNames.push(basename(file, '.svg'));
    }

    iconNames.sort();

    // Generate TypeScript Types
    const typeContent = `// This file is auto-generated by './scripts/buildIcons.ts'. Do not edit manually.
                        export type IconType =
                          | '${iconNames.join("'\n  | '")}';
                        `;
    await mkdir(dirname(TYPES_FILE), { recursive: true });
    await writeFile(TYPES_FILE, typeContent, 'utf-8');

    // Generate Markdown Gallery
    const relativePathToIcons = '../../../assets/images/icons';
    let mdContent = `# Icon Gallery\n\n| Icon | Name |\n| :---: | :--- |\n`;

    for (const name of iconNames) {
      mdContent += `| ![](${relativePathToIcons}/${name}.svg) | \`${name}\` |\n`;
    }

    await writeFile(README_FILE, mdContent, 'utf-8');

    console.log(`${iconNames.length} icons normalized`);
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

generateIconTypes();
