/** @type {import('tailwindcss').Config} */

module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      backgroundImage: {
        'rose-pink-purple':
          'linear-gradient(to bottom right, theme(colors.rose[50]), theme(colors.pink[50]), theme(colors.purple[50]))',
      },
      colors: {
        // catppuccin colors (e.g. macchiato) from: https://catppuccin.com/palette/
        'latte-rosewater': '#dc8a78',
        'latte-flamingo': '#dd7878',
        'latte-pink': '#ea76cb',
        'latte-mauve': '#8839ef',
        'latte-red': '#d20f39',
        'latte-maroon': '#e64553',
        'latte-peach': '#fe640b',
        'latte-yellow': '#df8e1d',
        'latte-green': '#40a02b',
        'latte-teal': '#179299',
        'latte-sky': '#04a5e5',
        'latte-sapphire': '#209fb5',
        'latte-blue': '#1e66f5',
        'latte-lavender': '#7287fd',
        'latte-text': '#4c4f69',
        'latte-subtext-1': '#5c5f77',
        'latte-subtext-0': '#6c6f85',
        'latte-overlay-2': '#7c7f93',
        'latte-overlay-1': '#8c8fa1',
        'latte-overlay-0': '#9ca0b0',
        'latte-surface-2': '#acb0be',
        'latte-surface-1': '#bcc0cc',
        'latte-surface-0': '#ccd0da',
        'latte-base': '#eff1f5',
        'latte-mantle': '#e6e9ef',
        'latte-crust': '#dce0e8',
        'frappe-rosewater': '#f2d5cf',
        'frappe-flamingo': '#eebebe',
        'frappe-pink': '#f4b8e4',
        'frappe-mauve': '#ca9ee6',
        'frappe-red': '#e78284',
        'frappe-maroon': '#ea999c',
        'frappe-peach': '#ef9f76',
        'frappe-yellow': '#e5c890',
        'frappe-green': '#a6d189',
        'frappe-teal': '#81c8be',
        'frappe-sky': '#99d1db',
        'frappe-sapphire': '#85c1dc',
        'frappe-blue': '#8caaee',
        'frappe-lavender': '#babbf1',
        'frappe-text': '#c6d0f5',
        'frappe-subtext-1': '#b5bfe2',
        'frappe-subtext-0': '#a5adce',
        'frappe-overlay-2': '#949cbb',
        'frappe-overlay-1': '#838ba7',
        'frappe-overlay-0': '#737994',
        'frappe-surface-2': '#626880',
        'frappe-surface-1': '#51576d',
        'frappe-surface-0': '#414559',
        'frappe-base': '#303446',
        'frappe-mantle': '#292c3c',
        'frappe-crust': '#232634',
      },
    },
  },
};
