// This file is auto-generated by './scripts/buildIcons.ts'. Do not edit manually.
export type IconType =
  | 'icon-bell'
  | 'icon-close'
  | 'icon-email'
  | 'icon-filters'
  | 'icon-fire'
  | 'icon-heart'
  | 'icon-heart-full'
  | 'icon-info'
  | 'icon-locker-locked'
  | 'icon-reply'
  | 'icon-settings'
  | 'icon-spinner'
  | 'icon-star'
  | 'icon-star-full'
  | 'icon-user-add';
